#!/usr/bin/env bash
# Script that will display information about subdomains

printSubdomain () {
    subdomain="$2"
    RECORD=$(dig "$1" | awk '/IN/ && $1 !~ /^;/ {print $4}')
    NAME=$(dig "$1" | awk '/IN/ && $1 !~ /^;/ {print $5}')
    echo "The subdomain ${subdomain} is a ${RECORD} record and points to ${NAME}"
}

if [ -z "$2" ]; then
    printSubdomain "www.$1" "www"
    printSubdomain "lb-01.$1" "lb-01"
    printSubdomain "web-01.$1" "web-01"
    printSubdomain "web-02.$1" "web-02"
else
    printSubdomain "$2.$1" $2
fi
