#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy=1.8.\*
echo "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance roundrobin
   mode http
   server 22146-web-01 18.232.54.29:80 check
   server 22146-web-02 44.200.194.124:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
