#!/usr/bin/env bash

#display hours from 0 to 12
#display minutes from 1 to 59

h=0

while [ $h -le 12 ]
do
    echo "Hour: $h"
    i=1
    while [ $i -le 59 ]
    do
		echo "$i"
        ((i++))
    done
    ((h++))
done
