#!/usr/bin/env bash
# install the ufw firewall and setup a few rules

sudo apt-get -y update 

# UFW shopuld be installed by default in linux
sudo apt-get install -y ufw

# Check ufw is installed
sudo ufw status

# Allow ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Check the ports are correctly added
sudo ufw show added

# Enable afw
echo "y" | sudo ufw enable

# Check ufw is correctly enabled
sudo ufw status
